//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "TipodeGastoGasto", "TipodeGasto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.TipodeGasto), "Gasto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Gasto))]
[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "VehiculoGasto", "Vehiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Vehiculo), "Gasto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Gasto))]
[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "ChoferTurno", "Chofer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Chofer), "Turno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Turno))]
[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "VehiculoTurno", "Vehiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Vehiculo), "Turno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Turno))]
[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "GastoTurno", "Gasto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Gasto), "Turno", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Modelo.Turno))]
[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "CuentaCorrienteTurno", "CuentaCorriente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.CuentaCorriente), "Turno", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Turno))]
[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "EmpresaCuentaCorriente", "Empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Empresa), "CuentaCorriente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.CuentaCorriente))]

#endregion

namespace Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SistFlota_ModeloDatosContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SistFlota_ModeloDatosContainer usando la cadena de conexión encontrada en la sección 'SistFlota_ModeloDatosContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public SistFlota_ModeloDatosContainer() : base("name=SistFlota_ModeloDatosContainer", "SistFlota_ModeloDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SistFlota_ModeloDatosContainer.
        /// </summary>
        public SistFlota_ModeloDatosContainer(string connectionString) : base(connectionString, "SistFlota_ModeloDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SistFlota_ModeloDatosContainer.
        /// </summary>
        public SistFlota_ModeloDatosContainer(EntityConnection connection) : base(connection, "SistFlota_ModeloDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipodeGasto> TiposdeGasto
        {
            get
            {
                if ((_TiposdeGasto == null))
                {
                    _TiposdeGasto = base.CreateObjectSet<TipodeGasto>("TiposdeGasto");
                }
                return _TiposdeGasto;
            }
        }
        private ObjectSet<TipodeGasto> _TiposdeGasto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Gasto> Gastos
        {
            get
            {
                if ((_Gastos == null))
                {
                    _Gastos = base.CreateObjectSet<Gasto>("Gastos");
                }
                return _Gastos;
            }
        }
        private ObjectSet<Gasto> _Gastos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Vehiculo> Vehiculos
        {
            get
            {
                if ((_Vehiculos == null))
                {
                    _Vehiculos = base.CreateObjectSet<Vehiculo>("Vehiculos");
                }
                return _Vehiculos;
            }
        }
        private ObjectSet<Vehiculo> _Vehiculos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Chofer> Choferes
        {
            get
            {
                if ((_Choferes == null))
                {
                    _Choferes = base.CreateObjectSet<Chofer>("Choferes");
                }
                return _Choferes;
            }
        }
        private ObjectSet<Chofer> _Choferes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empresa> Empresas
        {
            get
            {
                if ((_Empresas == null))
                {
                    _Empresas = base.CreateObjectSet<Empresa>("Empresas");
                }
                return _Empresas;
            }
        }
        private ObjectSet<Empresa> _Empresas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Turno> Turnos
        {
            get
            {
                if ((_Turnos == null))
                {
                    _Turnos = base.CreateObjectSet<Turno>("Turnos");
                }
                return _Turnos;
            }
        }
        private ObjectSet<Turno> _Turnos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CuentaCorriente> CuentasCorrientes
        {
            get
            {
                if ((_CuentasCorrientes == null))
                {
                    _CuentasCorrientes = base.CreateObjectSet<CuentaCorriente>("CuentasCorrientes");
                }
                return _CuentasCorrientes;
            }
        }
        private ObjectSet<CuentaCorriente> _CuentasCorrientes;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TiposdeGasto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTiposdeGasto(TipodeGasto tipodeGasto)
        {
            base.AddObject("TiposdeGasto", tipodeGasto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Gastos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToGastos(Gasto gasto)
        {
            base.AddObject("Gastos", gasto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Vehiculos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVehiculos(Vehiculo vehiculo)
        {
            base.AddObject("Vehiculos", vehiculo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Choferes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToChoferes(Chofer chofer)
        {
            base.AddObject("Choferes", chofer);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Empresas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpresas(Empresa empresa)
        {
            base.AddObject("Empresas", empresa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Turnos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTurnos(Turno turno)
        {
            base.AddObject("Turnos", turno);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CuentasCorrientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCuentasCorrientes(CuentaCorriente cuentaCorriente)
        {
            base.AddObject("CuentasCorrientes", cuentaCorriente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Chofer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Chofer : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Chofer.
        /// </summary>
        /// <param name="documento">Valor inicial de la propiedad Documento.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad Apellido.</param>
        /// <param name="licencia">Valor inicial de la propiedad Licencia.</param>
        /// <param name="domicilio">Valor inicial de la propiedad Domicilio.</param>
        /// <param name="localidad">Valor inicial de la propiedad Localidad.</param>
        /// <param name="fechaNacimiento">Valor inicial de la propiedad FechaNacimiento.</param>
        public static Chofer CreateChofer(global::System.Int32 documento, global::System.String nombre, global::System.String apellido, global::System.String licencia, global::System.String domicilio, global::System.String localidad, global::System.DateTime fechaNacimiento)
        {
            Chofer chofer = new Chofer();
            chofer.Documento = documento;
            chofer.Nombre = nombre;
            chofer.Apellido = apellido;
            chofer.Licencia = licencia;
            chofer.Domicilio = domicilio;
            chofer.Localidad = localidad;
            chofer.FechaNacimiento = fechaNacimiento;
            return chofer;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Documento
        {
            get
            {
                return _Documento;
            }
            set
            {
                if (_Documento != value)
                {
                    OnDocumentoChanging(value);
                    ReportPropertyChanging("Documento");
                    _Documento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Documento");
                    OnDocumentoChanged();
                }
            }
        }
        private global::System.Int32 _Documento;
        partial void OnDocumentoChanging(global::System.Int32 value);
        partial void OnDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Licencia
        {
            get
            {
                return _Licencia;
            }
            set
            {
                OnLicenciaChanging(value);
                ReportPropertyChanging("Licencia");
                _Licencia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Licencia");
                OnLicenciaChanged();
            }
        }
        private global::System.String _Licencia;
        partial void OnLicenciaChanging(global::System.String value);
        partial void OnLicenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Domicilio
        {
            get
            {
                return _Domicilio;
            }
            set
            {
                OnDomicilioChanging(value);
                ReportPropertyChanging("Domicilio");
                _Domicilio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Domicilio");
                OnDomicilioChanged();
            }
        }
        private global::System.String _Domicilio;
        partial void OnDomicilioChanging(global::System.String value);
        partial void OnDomicilioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Localidad
        {
            get
            {
                return _Localidad;
            }
            set
            {
                OnLocalidadChanging(value);
                ReportPropertyChanging("Localidad");
                _Localidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Localidad");
                OnLocalidadChanged();
            }
        }
        private global::System.String _Localidad;
        partial void OnLocalidadChanging(global::System.String value);
        partial void OnLocalidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private global::System.DateTime _FechaNacimiento;
        partial void OnFechaNacimientoChanging(global::System.DateTime value);
        partial void OnFechaNacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Foto
        {
            get
            {
                return StructuralObject.GetValidValue(_Foto);
            }
            set
            {
                OnFotoChanging(value);
                ReportPropertyChanging("Foto");
                _Foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Foto");
                OnFotoChanged();
            }
        }
        private global::System.Byte[] _Foto;
        partial void OnFotoChanging(global::System.Byte[] value);
        partial void OnFotoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "ChoferTurno", "Turno")]
        public EntityCollection<Turno> Turno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Turno>("SistFlota_ModeloDatos.ChoferTurno", "Turno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Turno>("SistFlota_ModeloDatos.ChoferTurno", "Turno", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="documento">Valor inicial de la propiedad Documento.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad Apellido.</param>
        /// <param name="fechaNacimiento">Valor inicial de la propiedad FechaNacimiento.</param>
        /// <param name="domicilio">Valor inicial de la propiedad Domicilio.</param>
        /// <param name="telefono">Valor inicial de la propiedad Telefono.</param>
        /// <param name="correo">Valor inicial de la propiedad Correo.</param>
        /// <param name="empresaCUIL">Valor inicial de la propiedad EmpresaCUIL.</param>
        public static Cliente CreateCliente(global::System.Int32 documento, global::System.String nombre, global::System.String apellido, global::System.DateTime fechaNacimiento, global::System.String domicilio, global::System.String telefono, global::System.String correo, global::System.Int32 empresaCUIL)
        {
            Cliente cliente = new Cliente();
            cliente.Documento = documento;
            cliente.Nombre = nombre;
            cliente.Apellido = apellido;
            cliente.FechaNacimiento = fechaNacimiento;
            cliente.Domicilio = domicilio;
            cliente.Telefono = telefono;
            cliente.Correo = correo;
            cliente.EmpresaCUIL = empresaCUIL;
            return cliente;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Documento
        {
            get
            {
                return _Documento;
            }
            set
            {
                if (_Documento != value)
                {
                    OnDocumentoChanging(value);
                    ReportPropertyChanging("Documento");
                    _Documento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Documento");
                    OnDocumentoChanged();
                }
            }
        }
        private global::System.Int32 _Documento;
        partial void OnDocumentoChanging(global::System.Int32 value);
        partial void OnDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private global::System.DateTime _FechaNacimiento;
        partial void OnFechaNacimientoChanging(global::System.DateTime value);
        partial void OnFechaNacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Domicilio
        {
            get
            {
                return _Domicilio;
            }
            set
            {
                OnDomicilioChanging(value);
                ReportPropertyChanging("Domicilio");
                _Domicilio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Domicilio");
                OnDomicilioChanged();
            }
        }
        private global::System.String _Domicilio;
        partial void OnDomicilioChanging(global::System.String value);
        partial void OnDomicilioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpresaCUIL
        {
            get
            {
                return _EmpresaCUIL;
            }
            set
            {
                OnEmpresaCUILChanging(value);
                ReportPropertyChanging("EmpresaCUIL");
                _EmpresaCUIL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmpresaCUIL");
                OnEmpresaCUILChanged();
            }
        }
        private global::System.Int32 _EmpresaCUIL;
        partial void OnEmpresaCUILChanging(global::System.Int32 value);
        partial void OnEmpresaCUILChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="CuentaCorriente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CuentaCorriente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CuentaCorriente.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        /// <param name="estado">Valor inicial de la propiedad Estado.</param>
        public static CuentaCorriente CreateCuentaCorriente(global::System.Int32 id, global::System.DateTime fecha, global::System.Decimal monto, global::System.String estado)
        {
            CuentaCorriente cuentaCorriente = new CuentaCorriente();
            cuentaCorriente.Id = id;
            cuentaCorriente.Fecha = fecha;
            cuentaCorriente.Monto = monto;
            cuentaCorriente.Estado = estado;
            return cuentaCorriente;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "CuentaCorrienteTurno", "Turno")]
        public Turno Turno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turno>("SistFlota_ModeloDatos.CuentaCorrienteTurno", "Turno").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turno>("SistFlota_ModeloDatos.CuentaCorrienteTurno", "Turno").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Turno> TurnoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turno>("SistFlota_ModeloDatos.CuentaCorrienteTurno", "Turno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Turno>("SistFlota_ModeloDatos.CuentaCorrienteTurno", "Turno", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "EmpresaCuentaCorriente", "Empresa")]
        public Empresa Empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("SistFlota_ModeloDatos.EmpresaCuentaCorriente", "Empresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("SistFlota_ModeloDatos.EmpresaCuentaCorriente", "Empresa").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empresa> EmpresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("SistFlota_ModeloDatos.EmpresaCuentaCorriente", "Empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empresa>("SistFlota_ModeloDatos.EmpresaCuentaCorriente", "Empresa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empresa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empresa.
        /// </summary>
        /// <param name="cuit">Valor inicial de la propiedad Cuit.</param>
        /// <param name="razonSocial">Valor inicial de la propiedad RazonSocial.</param>
        /// <param name="domicilio">Valor inicial de la propiedad Domicilio.</param>
        /// <param name="telefono">Valor inicial de la propiedad Telefono.</param>
        /// <param name="localidad">Valor inicial de la propiedad Localidad.</param>
        /// <param name="correo">Valor inicial de la propiedad Correo.</param>
        public static Empresa CreateEmpresa(global::System.Int32 cuit, global::System.String razonSocial, global::System.String domicilio, global::System.String telefono, global::System.String localidad, global::System.String correo)
        {
            Empresa empresa = new Empresa();
            empresa.Cuit = cuit;
            empresa.RazonSocial = razonSocial;
            empresa.Domicilio = domicilio;
            empresa.Telefono = telefono;
            empresa.Localidad = localidad;
            empresa.Correo = correo;
            return empresa;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cuit
        {
            get
            {
                return _Cuit;
            }
            set
            {
                if (_Cuit != value)
                {
                    OnCuitChanging(value);
                    ReportPropertyChanging("Cuit");
                    _Cuit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cuit");
                    OnCuitChanged();
                }
            }
        }
        private global::System.Int32 _Cuit;
        partial void OnCuitChanging(global::System.Int32 value);
        partial void OnCuitChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Domicilio
        {
            get
            {
                return _Domicilio;
            }
            set
            {
                OnDomicilioChanging(value);
                ReportPropertyChanging("Domicilio");
                _Domicilio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Domicilio");
                OnDomicilioChanged();
            }
        }
        private global::System.String _Domicilio;
        partial void OnDomicilioChanging(global::System.String value);
        partial void OnDomicilioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Localidad
        {
            get
            {
                return _Localidad;
            }
            set
            {
                OnLocalidadChanging(value);
                ReportPropertyChanging("Localidad");
                _Localidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Localidad");
                OnLocalidadChanged();
            }
        }
        private global::System.String _Localidad;
        partial void OnLocalidadChanging(global::System.String value);
        partial void OnLocalidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "EmpresaCuentaCorriente", "CuentaCorriente")]
        public EntityCollection<CuentaCorriente> CuentaCorriente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CuentaCorriente>("SistFlota_ModeloDatos.EmpresaCuentaCorriente", "CuentaCorriente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CuentaCorriente>("SistFlota_ModeloDatos.EmpresaCuentaCorriente", "CuentaCorriente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Gasto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gasto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Gasto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        /// <param name="estado">Valor inicial de la propiedad Estado.</param>
        /// <param name="fechaVencimiento">Valor inicial de la propiedad FechaVencimiento.</param>
        /// <param name="usuario">Valor inicial de la propiedad Usuario.</param>
        /// <param name="fechayHora">Valor inicial de la propiedad FechayHora.</param>
        /// <param name="operacion">Valor inicial de la propiedad Operacion.</param>
        public static Gasto CreateGasto(global::System.Int32 id, global::System.String descripcion, global::System.Decimal monto, global::System.String estado, global::System.DateTime fechaVencimiento, global::System.String usuario, global::System.DateTime fechayHora, global::System.String operacion)
        {
            Gasto gasto = new Gasto();
            gasto.Id = id;
            gasto.Descripcion = descripcion;
            gasto.Monto = monto;
            gasto.Estado = estado;
            gasto.FechaVencimiento = fechaVencimiento;
            gasto.Usuario = usuario;
            gasto.FechayHora = fechayHora;
            gasto.Operacion = operacion;
            return gasto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaVencimiento
        {
            get
            {
                return _FechaVencimiento;
            }
            set
            {
                OnFechaVencimientoChanging(value);
                ReportPropertyChanging("FechaVencimiento");
                _FechaVencimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaVencimiento");
                OnFechaVencimientoChanged();
            }
        }
        private global::System.DateTime _FechaVencimiento;
        partial void OnFechaVencimientoChanging(global::System.DateTime value);
        partial void OnFechaVencimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HoraEmision
        {
            get
            {
                return _HoraEmision;
            }
            set
            {
                OnHoraEmisionChanging(value);
                ReportPropertyChanging("HoraEmision");
                _HoraEmision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoraEmision");
                OnHoraEmisionChanged();
            }
        }
        private Nullable<global::System.DateTime> _HoraEmision;
        partial void OnHoraEmisionChanging(Nullable<global::System.DateTime> value);
        partial void OnHoraEmisionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaEmision
        {
            get
            {
                return _FechaEmision;
            }
            set
            {
                OnFechaEmisionChanging(value);
                ReportPropertyChanging("FechaEmision");
                _FechaEmision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaEmision");
                OnFechaEmisionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaEmision;
        partial void OnFechaEmisionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaEmisionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechayHora
        {
            get
            {
                return _FechayHora;
            }
            set
            {
                OnFechayHoraChanging(value);
                ReportPropertyChanging("FechayHora");
                _FechayHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechayHora");
                OnFechayHoraChanged();
            }
        }
        private global::System.DateTime _FechayHora;
        partial void OnFechayHoraChanging(global::System.DateTime value);
        partial void OnFechayHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Operacion
        {
            get
            {
                return _Operacion;
            }
            set
            {
                OnOperacionChanging(value);
                ReportPropertyChanging("Operacion");
                _Operacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Operacion");
                OnOperacionChanged();
            }
        }
        private global::System.String _Operacion;
        partial void OnOperacionChanging(global::System.String value);
        partial void OnOperacionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "TipodeGastoGasto", "TipodeGasto")]
        public TipodeGasto TipodeGasto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipodeGasto> TipodeGastoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "VehiculoGasto", "Vehiculo")]
        public Vehiculo Vehiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehiculo> VehiculoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "GastoTurno", "Turno")]
        public Turno Turno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turno>("SistFlota_ModeloDatos.GastoTurno", "Turno").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turno>("SistFlota_ModeloDatos.GastoTurno", "Turno").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Turno> TurnoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turno>("SistFlota_ModeloDatos.GastoTurno", "Turno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Turno>("SistFlota_ModeloDatos.GastoTurno", "Turno", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="TipodeGasto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipodeGasto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipodeGasto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        public static TipodeGasto CreateTipodeGasto(global::System.Int32 id, global::System.String descripcion)
        {
            TipodeGasto tipodeGasto = new TipodeGasto();
            tipodeGasto.Id = id;
            tipodeGasto.Descripcion = descripcion;
            return tipodeGasto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "TipodeGastoGasto", "Gasto")]
        public EntityCollection<Gasto> Gasto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Gasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "Gasto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Gasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "Gasto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Turno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Turno : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Turno.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="fechaInicio">Valor inicial de la propiedad FechaInicio.</param>
        /// <param name="horaInicio">Valor inicial de la propiedad HoraInicio.</param>
        /// <param name="fechaFin">Valor inicial de la propiedad FechaFin.</param>
        /// <param name="horaFin">Valor inicial de la propiedad HoraFin.</param>
        /// <param name="kmRecorridos">Valor inicial de la propiedad KmRecorridos.</param>
        /// <param name="kmOcupados">Valor inicial de la propiedad KmOcupados.</param>
        /// <param name="cantidadViajes">Valor inicial de la propiedad CantidadViajes.</param>
        /// <param name="recaudacionEfectivo">Valor inicial de la propiedad RecaudacionEfectivo.</param>
        /// <param name="comentarios">Valor inicial de la propiedad Comentarios.</param>
        public static Turno CreateTurno(global::System.Int32 id, global::System.DateTime fechaInicio, global::System.DateTime horaInicio, global::System.DateTime fechaFin, global::System.DateTime horaFin, global::System.Decimal kmRecorridos, global::System.Decimal kmOcupados, global::System.Int32 cantidadViajes, global::System.Decimal recaudacionEfectivo, global::System.String comentarios)
        {
            Turno turno = new Turno();
            turno.Id = id;
            turno.FechaInicio = fechaInicio;
            turno.HoraInicio = horaInicio;
            turno.FechaFin = fechaFin;
            turno.HoraFin = horaFin;
            turno.KmRecorridos = kmRecorridos;
            turno.KmOcupados = kmOcupados;
            turno.CantidadViajes = cantidadViajes;
            turno.RecaudacionEfectivo = recaudacionEfectivo;
            turno.Comentarios = comentarios;
            return turno;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private global::System.DateTime _FechaInicio;
        partial void OnFechaInicioChanging(global::System.DateTime value);
        partial void OnFechaInicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HoraInicio
        {
            get
            {
                return _HoraInicio;
            }
            set
            {
                OnHoraInicioChanging(value);
                ReportPropertyChanging("HoraInicio");
                _HoraInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoraInicio");
                OnHoraInicioChanged();
            }
        }
        private global::System.DateTime _HoraInicio;
        partial void OnHoraInicioChanging(global::System.DateTime value);
        partial void OnHoraInicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaFin
        {
            get
            {
                return _FechaFin;
            }
            set
            {
                OnFechaFinChanging(value);
                ReportPropertyChanging("FechaFin");
                _FechaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFin");
                OnFechaFinChanged();
            }
        }
        private global::System.DateTime _FechaFin;
        partial void OnFechaFinChanging(global::System.DateTime value);
        partial void OnFechaFinChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HoraFin
        {
            get
            {
                return _HoraFin;
            }
            set
            {
                OnHoraFinChanging(value);
                ReportPropertyChanging("HoraFin");
                _HoraFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoraFin");
                OnHoraFinChanged();
            }
        }
        private global::System.DateTime _HoraFin;
        partial void OnHoraFinChanging(global::System.DateTime value);
        partial void OnHoraFinChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal KmRecorridos
        {
            get
            {
                return _KmRecorridos;
            }
            set
            {
                OnKmRecorridosChanging(value);
                ReportPropertyChanging("KmRecorridos");
                _KmRecorridos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KmRecorridos");
                OnKmRecorridosChanged();
            }
        }
        private global::System.Decimal _KmRecorridos;
        partial void OnKmRecorridosChanging(global::System.Decimal value);
        partial void OnKmRecorridosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal KmOcupados
        {
            get
            {
                return _KmOcupados;
            }
            set
            {
                OnKmOcupadosChanging(value);
                ReportPropertyChanging("KmOcupados");
                _KmOcupados = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KmOcupados");
                OnKmOcupadosChanged();
            }
        }
        private global::System.Decimal _KmOcupados;
        partial void OnKmOcupadosChanging(global::System.Decimal value);
        partial void OnKmOcupadosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CantidadViajes
        {
            get
            {
                return _CantidadViajes;
            }
            set
            {
                OnCantidadViajesChanging(value);
                ReportPropertyChanging("CantidadViajes");
                _CantidadViajes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadViajes");
                OnCantidadViajesChanged();
            }
        }
        private global::System.Int32 _CantidadViajes;
        partial void OnCantidadViajesChanging(global::System.Int32 value);
        partial void OnCantidadViajesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RecaudacionEfectivo
        {
            get
            {
                return _RecaudacionEfectivo;
            }
            set
            {
                OnRecaudacionEfectivoChanging(value);
                ReportPropertyChanging("RecaudacionEfectivo");
                _RecaudacionEfectivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecaudacionEfectivo");
                OnRecaudacionEfectivoChanged();
            }
        }
        private global::System.Decimal _RecaudacionEfectivo;
        partial void OnRecaudacionEfectivoChanging(global::System.Decimal value);
        partial void OnRecaudacionEfectivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comentarios
        {
            get
            {
                return _Comentarios;
            }
            set
            {
                OnComentariosChanging(value);
                ReportPropertyChanging("Comentarios");
                _Comentarios = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comentarios");
                OnComentariosChanged();
            }
        }
        private global::System.String _Comentarios;
        partial void OnComentariosChanging(global::System.String value);
        partial void OnComentariosChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "ChoferTurno", "Chofer")]
        public Chofer Chofer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Chofer>("SistFlota_ModeloDatos.ChoferTurno", "Chofer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Chofer>("SistFlota_ModeloDatos.ChoferTurno", "Chofer").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Chofer> ChoferReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Chofer>("SistFlota_ModeloDatos.ChoferTurno", "Chofer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Chofer>("SistFlota_ModeloDatos.ChoferTurno", "Chofer", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "VehiculoTurno", "Vehiculo")]
        public Vehiculo Vehiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoTurno", "Vehiculo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoTurno", "Vehiculo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehiculo> VehiculoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoTurno", "Vehiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoTurno", "Vehiculo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "GastoTurno", "Gasto")]
        public EntityCollection<Gasto> Gasto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Gasto>("SistFlota_ModeloDatos.GastoTurno", "Gasto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Gasto>("SistFlota_ModeloDatos.GastoTurno", "Gasto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "CuentaCorrienteTurno", "CuentaCorriente")]
        public EntityCollection<CuentaCorriente> CuentaCorriente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CuentaCorriente>("SistFlota_ModeloDatos.CuentaCorrienteTurno", "CuentaCorriente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CuentaCorriente>("SistFlota_ModeloDatos.CuentaCorrienteTurno", "CuentaCorriente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Vehiculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehiculo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Vehiculo.
        /// </summary>
        /// <param name="patente">Valor inicial de la propiedad Patente.</param>
        /// <param name="marca">Valor inicial de la propiedad Marca.</param>
        /// <param name="modelo">Valor inicial de la propiedad Modelo.</param>
        /// <param name="año">Valor inicial de la propiedad Año.</param>
        /// <param name="color">Valor inicial de la propiedad Color.</param>
        /// <param name="kilometraje">Valor inicial de la propiedad Kilometraje.</param>
        public static Vehiculo CreateVehiculo(global::System.String patente, global::System.String marca, global::System.String modelo, global::System.Int32 año, global::System.String color, global::System.Int32 kilometraje)
        {
            Vehiculo vehiculo = new Vehiculo();
            vehiculo.Patente = patente;
            vehiculo.Marca = marca;
            vehiculo.Modelo = modelo;
            vehiculo.Año = año;
            vehiculo.Color = color;
            vehiculo.Kilometraje = kilometraje;
            return vehiculo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Patente
        {
            get
            {
                return _Patente;
            }
            set
            {
                if (_Patente != value)
                {
                    OnPatenteChanging(value);
                    ReportPropertyChanging("Patente");
                    _Patente = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Patente");
                    OnPatenteChanged();
                }
            }
        }
        private global::System.String _Patente;
        partial void OnPatenteChanging(global::System.String value);
        partial void OnPatenteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PatenteTaxi
        {
            get
            {
                return _PatenteTaxi;
            }
            set
            {
                OnPatenteTaxiChanging(value);
                ReportPropertyChanging("PatenteTaxi");
                _PatenteTaxi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatenteTaxi");
                OnPatenteTaxiChanged();
            }
        }
        private Nullable<global::System.Int32> _PatenteTaxi;
        partial void OnPatenteTaxiChanging(Nullable<global::System.Int32> value);
        partial void OnPatenteTaxiChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Año
        {
            get
            {
                return _Año;
            }
            set
            {
                OnAñoChanging(value);
                ReportPropertyChanging("Año");
                _Año = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Año");
                OnAñoChanged();
            }
        }
        private global::System.Int32 _Año;
        partial void OnAñoChanging(global::System.Int32 value);
        partial void OnAñoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Kilometraje
        {
            get
            {
                return _Kilometraje;
            }
            set
            {
                OnKilometrajeChanging(value);
                ReportPropertyChanging("Kilometraje");
                _Kilometraje = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kilometraje");
                OnKilometrajeChanged();
            }
        }
        private global::System.Int32 _Kilometraje;
        partial void OnKilometrajeChanging(global::System.Int32 value);
        partial void OnKilometrajeChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "VehiculoGasto", "Gasto")]
        public EntityCollection<Gasto> Gasto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Gasto>("SistFlota_ModeloDatos.VehiculoGasto", "Gasto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Gasto>("SistFlota_ModeloDatos.VehiculoGasto", "Gasto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "VehiculoTurno", "Turno")]
        public EntityCollection<Turno> Turno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Turno>("SistFlota_ModeloDatos.VehiculoTurno", "Turno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Turno>("SistFlota_ModeloDatos.VehiculoTurno", "Turno", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
