//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "TipodeGastoGasto", "TipodeGasto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.TipodeGasto), "Gasto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Gasto))]
[assembly: EdmRelationshipAttribute("SistFlota_ModeloDatos", "VehiculoGasto", "Vehiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Vehiculo), "Gasto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Gasto))]

#endregion

namespace Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SistFlota_ModeloDatosContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SistFlota_ModeloDatosContainer usando la cadena de conexión encontrada en la sección 'SistFlota_ModeloDatosContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public SistFlota_ModeloDatosContainer() : base("name=SistFlota_ModeloDatosContainer", "SistFlota_ModeloDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SistFlota_ModeloDatosContainer.
        /// </summary>
        public SistFlota_ModeloDatosContainer(string connectionString) : base(connectionString, "SistFlota_ModeloDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SistFlota_ModeloDatosContainer.
        /// </summary>
        public SistFlota_ModeloDatosContainer(EntityConnection connection) : base(connection, "SistFlota_ModeloDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipodeGasto> TiposdeGasto
        {
            get
            {
                if ((_TiposdeGasto == null))
                {
                    _TiposdeGasto = base.CreateObjectSet<TipodeGasto>("TiposdeGasto");
                }
                return _TiposdeGasto;
            }
        }
        private ObjectSet<TipodeGasto> _TiposdeGasto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Gasto> Gastos
        {
            get
            {
                if ((_Gastos == null))
                {
                    _Gastos = base.CreateObjectSet<Gasto>("Gastos");
                }
                return _Gastos;
            }
        }
        private ObjectSet<Gasto> _Gastos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Vehiculo> Vehiculos
        {
            get
            {
                if ((_Vehiculos == null))
                {
                    _Vehiculos = base.CreateObjectSet<Vehiculo>("Vehiculos");
                }
                return _Vehiculos;
            }
        }
        private ObjectSet<Vehiculo> _Vehiculos;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TiposdeGasto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTiposdeGasto(TipodeGasto tipodeGasto)
        {
            base.AddObject("TiposdeGasto", tipodeGasto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Gastos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToGastos(Gasto gasto)
        {
            base.AddObject("Gastos", gasto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Vehiculos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVehiculos(Vehiculo vehiculo)
        {
            base.AddObject("Vehiculos", vehiculo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Gasto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gasto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Gasto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        /// <param name="estado">Valor inicial de la propiedad Estado.</param>
        /// <param name="fechaVencimiento">Valor inicial de la propiedad FechaVencimiento.</param>
        /// <param name="usuario">Valor inicial de la propiedad Usuario.</param>
        /// <param name="fechayHora">Valor inicial de la propiedad FechayHora.</param>
        /// <param name="operacion">Valor inicial de la propiedad Operacion.</param>
        public static Gasto CreateGasto(global::System.Int32 id, global::System.String descripcion, global::System.Decimal monto, global::System.String estado, global::System.DateTime fechaVencimiento, global::System.String usuario, global::System.DateTime fechayHora, global::System.String operacion)
        {
            Gasto gasto = new Gasto();
            gasto.Id = id;
            gasto.Descripcion = descripcion;
            gasto.Monto = monto;
            gasto.Estado = estado;
            gasto.FechaVencimiento = fechaVencimiento;
            gasto.Usuario = usuario;
            gasto.FechayHora = fechayHora;
            gasto.Operacion = operacion;
            return gasto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaVencimiento
        {
            get
            {
                return _FechaVencimiento;
            }
            set
            {
                OnFechaVencimientoChanging(value);
                ReportPropertyChanging("FechaVencimiento");
                _FechaVencimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaVencimiento");
                OnFechaVencimientoChanged();
            }
        }
        private global::System.DateTime _FechaVencimiento;
        partial void OnFechaVencimientoChanging(global::System.DateTime value);
        partial void OnFechaVencimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HoraEmision
        {
            get
            {
                return _HoraEmision;
            }
            set
            {
                OnHoraEmisionChanging(value);
                ReportPropertyChanging("HoraEmision");
                _HoraEmision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoraEmision");
                OnHoraEmisionChanged();
            }
        }
        private Nullable<global::System.DateTime> _HoraEmision;
        partial void OnHoraEmisionChanging(Nullable<global::System.DateTime> value);
        partial void OnHoraEmisionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaEmision
        {
            get
            {
                return _FechaEmision;
            }
            set
            {
                OnFechaEmisionChanging(value);
                ReportPropertyChanging("FechaEmision");
                _FechaEmision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaEmision");
                OnFechaEmisionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaEmision;
        partial void OnFechaEmisionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaEmisionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechayHora
        {
            get
            {
                return _FechayHora;
            }
            set
            {
                OnFechayHoraChanging(value);
                ReportPropertyChanging("FechayHora");
                _FechayHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechayHora");
                OnFechayHoraChanged();
            }
        }
        private global::System.DateTime _FechayHora;
        partial void OnFechayHoraChanging(global::System.DateTime value);
        partial void OnFechayHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Operacion
        {
            get
            {
                return _Operacion;
            }
            set
            {
                OnOperacionChanging(value);
                ReportPropertyChanging("Operacion");
                _Operacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Operacion");
                OnOperacionChanged();
            }
        }
        private global::System.String _Operacion;
        partial void OnOperacionChanging(global::System.String value);
        partial void OnOperacionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "TipodeGastoGasto", "TipodeGasto")]
        public TipodeGasto TipodeGasto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipodeGasto> TipodeGastoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipodeGasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "TipodeGasto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "VehiculoGasto", "Vehiculo")]
        public Vehiculo Vehiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehiculo> VehiculoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehiculo>("SistFlota_ModeloDatos.VehiculoGasto", "Vehiculo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="TipodeGasto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipodeGasto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipodeGasto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        public static TipodeGasto CreateTipodeGasto(global::System.Int32 id, global::System.String descripcion)
        {
            TipodeGasto tipodeGasto = new TipodeGasto();
            tipodeGasto.Id = id;
            tipodeGasto.Descripcion = descripcion;
            return tipodeGasto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "TipodeGastoGasto", "Gasto")]
        public EntityCollection<Gasto> Gasto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Gasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "Gasto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Gasto>("SistFlota_ModeloDatos.TipodeGastoGasto", "Gasto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_ModeloDatos", Name="Vehiculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehiculo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Vehiculo.
        /// </summary>
        /// <param name="patente">Valor inicial de la propiedad Patente.</param>
        /// <param name="marca">Valor inicial de la propiedad Marca.</param>
        /// <param name="modelo">Valor inicial de la propiedad Modelo.</param>
        /// <param name="año">Valor inicial de la propiedad Año.</param>
        /// <param name="color">Valor inicial de la propiedad Color.</param>
        /// <param name="kilometraje">Valor inicial de la propiedad Kilometraje.</param>
        public static Vehiculo CreateVehiculo(global::System.String patente, global::System.String marca, global::System.String modelo, global::System.Int32 año, global::System.String color, global::System.Int32 kilometraje)
        {
            Vehiculo vehiculo = new Vehiculo();
            vehiculo.Patente = patente;
            vehiculo.Marca = marca;
            vehiculo.Modelo = modelo;
            vehiculo.Año = año;
            vehiculo.Color = color;
            vehiculo.Kilometraje = kilometraje;
            return vehiculo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Patente
        {
            get
            {
                return _Patente;
            }
            set
            {
                if (_Patente != value)
                {
                    OnPatenteChanging(value);
                    ReportPropertyChanging("Patente");
                    _Patente = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Patente");
                    OnPatenteChanged();
                }
            }
        }
        private global::System.String _Patente;
        partial void OnPatenteChanging(global::System.String value);
        partial void OnPatenteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PatenteTaxi
        {
            get
            {
                return _PatenteTaxi;
            }
            set
            {
                OnPatenteTaxiChanging(value);
                ReportPropertyChanging("PatenteTaxi");
                _PatenteTaxi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatenteTaxi");
                OnPatenteTaxiChanged();
            }
        }
        private Nullable<global::System.Int32> _PatenteTaxi;
        partial void OnPatenteTaxiChanging(Nullable<global::System.Int32> value);
        partial void OnPatenteTaxiChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Año
        {
            get
            {
                return _Año;
            }
            set
            {
                OnAñoChanging(value);
                ReportPropertyChanging("Año");
                _Año = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Año");
                OnAñoChanged();
            }
        }
        private global::System.Int32 _Año;
        partial void OnAñoChanging(global::System.Int32 value);
        partial void OnAñoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Kilometraje
        {
            get
            {
                return _Kilometraje;
            }
            set
            {
                OnKilometrajeChanging(value);
                ReportPropertyChanging("Kilometraje");
                _Kilometraje = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kilometraje");
                OnKilometrajeChanged();
            }
        }
        private global::System.Int32 _Kilometraje;
        partial void OnKilometrajeChanging(global::System.Int32 value);
        partial void OnKilometrajeChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_ModeloDatos", "VehiculoGasto", "Gasto")]
        public EntityCollection<Gasto> Gasto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Gasto>("SistFlota_ModeloDatos.VehiculoGasto", "Gasto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Gasto>("SistFlota_ModeloDatos.VehiculoGasto", "Gasto", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
