//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("SistFlota_Seguridad_Modelo", "PermisoPerfil", "Permiso", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.SEGURIDAD.Permiso), "Perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.SEGURIDAD.Perfil))]
[assembly: EdmRelationshipAttribute("SistFlota_Seguridad_Modelo", "FormularioPerfil", "Formulario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.SEGURIDAD.Formulario), "Perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.SEGURIDAD.Perfil))]
[assembly: EdmRelationshipAttribute("SistFlota_Seguridad_Modelo", "GrupoPerfil", "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.SEGURIDAD.Grupo), "Perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.SEGURIDAD.Perfil))]
[assembly: EdmRelationshipAttribute("SistFlota_Seguridad_Modelo", "UsuarioGrupo", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.SEGURIDAD.Usuario), "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.SEGURIDAD.Grupo))]

#endregion

namespace Modelo.SEGURIDAD
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SistFlota_Seguridad_ModeloContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SistFlota_Seguridad_ModeloContainer usando la cadena de conexión encontrada en la sección 'SistFlota_Seguridad_ModeloContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public SistFlota_Seguridad_ModeloContainer() : base("name=SistFlota_Seguridad_ModeloContainer", "SistFlota_Seguridad_ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SistFlota_Seguridad_ModeloContainer.
        /// </summary>
        public SistFlota_Seguridad_ModeloContainer(string connectionString) : base(connectionString, "SistFlota_Seguridad_ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SistFlota_Seguridad_ModeloContainer.
        /// </summary>
        public SistFlota_Seguridad_ModeloContainer(EntityConnection connection) : base(connection, "SistFlota_Seguridad_ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Grupo> Grupos
        {
            get
            {
                if ((_Grupos == null))
                {
                    _Grupos = base.CreateObjectSet<Grupo>("Grupos");
                }
                return _Grupos;
            }
        }
        private ObjectSet<Grupo> _Grupos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Perfil> Perfiles
        {
            get
            {
                if ((_Perfiles == null))
                {
                    _Perfiles = base.CreateObjectSet<Perfil>("Perfiles");
                }
                return _Perfiles;
            }
        }
        private ObjectSet<Perfil> _Perfiles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Permiso> Permisos
        {
            get
            {
                if ((_Permisos == null))
                {
                    _Permisos = base.CreateObjectSet<Permiso>("Permisos");
                }
                return _Permisos;
            }
        }
        private ObjectSet<Permiso> _Permisos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Formulario> Formularios
        {
            get
            {
                if ((_Formularios == null))
                {
                    _Formularios = base.CreateObjectSet<Formulario>("Formularios");
                }
                return _Formularios;
            }
        }
        private ObjectSet<Formulario> _Formularios;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Grupos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToGrupos(Grupo grupo)
        {
            base.AddObject("Grupos", grupo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Perfiles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPerfiles(Perfil perfil)
        {
            base.AddObject("Perfiles", perfil);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Permisos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPermisos(Permiso permiso)
        {
            base.AddObject("Permisos", permiso);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Formularios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFormularios(Formulario formulario)
        {
            base.AddObject("Formularios", formulario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_Seguridad_Modelo", Name="Formulario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Formulario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Formulario.
        /// </summary>
        /// <param name="iDformulario">Valor inicial de la propiedad IDformulario.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        public static Formulario CreateFormulario(global::System.String iDformulario, global::System.String descripcion)
        {
            Formulario formulario = new Formulario();
            formulario.IDformulario = iDformulario;
            formulario.Descripcion = descripcion;
            return formulario;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDformulario
        {
            get
            {
                return _IDformulario;
            }
            set
            {
                if (_IDformulario != value)
                {
                    OnIDformularioChanging(value);
                    ReportPropertyChanging("IDformulario");
                    _IDformulario = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IDformulario");
                    OnIDformularioChanged();
                }
            }
        }
        private global::System.String _IDformulario;
        partial void OnIDformularioChanging(global::System.String value);
        partial void OnIDformularioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "FormularioPerfil", "Perfil")]
        public EntityCollection<Perfil> Perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Perfil>("SistFlota_Seguridad_Modelo.FormularioPerfil", "Perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Perfil>("SistFlota_Seguridad_Modelo.FormularioPerfil", "Perfil", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_Seguridad_Modelo", Name="Grupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grupo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Grupo.
        /// </summary>
        /// <param name="iDgrupo">Valor inicial de la propiedad IDgrupo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        public static Grupo CreateGrupo(global::System.String iDgrupo, global::System.String descripcion)
        {
            Grupo grupo = new Grupo();
            grupo.IDgrupo = iDgrupo;
            grupo.Descripcion = descripcion;
            return grupo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDgrupo
        {
            get
            {
                return _IDgrupo;
            }
            set
            {
                if (_IDgrupo != value)
                {
                    OnIDgrupoChanging(value);
                    ReportPropertyChanging("IDgrupo");
                    _IDgrupo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IDgrupo");
                    OnIDgrupoChanged();
                }
            }
        }
        private global::System.String _IDgrupo;
        partial void OnIDgrupoChanging(global::System.String value);
        partial void OnIDgrupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "GrupoPerfil", "Perfil")]
        public EntityCollection<Perfil> Perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Perfil>("SistFlota_Seguridad_Modelo.GrupoPerfil", "Perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Perfil>("SistFlota_Seguridad_Modelo.GrupoPerfil", "Perfil", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "UsuarioGrupo", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("SistFlota_Seguridad_Modelo.UsuarioGrupo", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("SistFlota_Seguridad_Modelo.UsuarioGrupo", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_Seguridad_Modelo", Name="Perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Perfil : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Perfil.
        /// </summary>
        /// <param name="iDperfil">Valor inicial de la propiedad IDperfil.</param>
        public static Perfil CreatePerfil(global::System.Int32 iDperfil)
        {
            Perfil perfil = new Perfil();
            perfil.IDperfil = iDperfil;
            return perfil;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDperfil
        {
            get
            {
                return _IDperfil;
            }
            set
            {
                if (_IDperfil != value)
                {
                    OnIDperfilChanging(value);
                    ReportPropertyChanging("IDperfil");
                    _IDperfil = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDperfil");
                    OnIDperfilChanged();
                }
            }
        }
        private global::System.Int32 _IDperfil;
        partial void OnIDperfilChanging(global::System.Int32 value);
        partial void OnIDperfilChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "PermisoPerfil", "Permiso")]
        public Permiso Permiso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Permiso>("SistFlota_Seguridad_Modelo.PermisoPerfil", "Permiso").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Permiso>("SistFlota_Seguridad_Modelo.PermisoPerfil", "Permiso").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Permiso> PermisoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Permiso>("SistFlota_Seguridad_Modelo.PermisoPerfil", "Permiso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Permiso>("SistFlota_Seguridad_Modelo.PermisoPerfil", "Permiso", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "FormularioPerfil", "Formulario")]
        public Formulario Formulario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Formulario>("SistFlota_Seguridad_Modelo.FormularioPerfil", "Formulario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Formulario>("SistFlota_Seguridad_Modelo.FormularioPerfil", "Formulario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Formulario> FormularioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Formulario>("SistFlota_Seguridad_Modelo.FormularioPerfil", "Formulario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Formulario>("SistFlota_Seguridad_Modelo.FormularioPerfil", "Formulario", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "GrupoPerfil", "Grupo")]
        public Grupo Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("SistFlota_Seguridad_Modelo.GrupoPerfil", "Grupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("SistFlota_Seguridad_Modelo.GrupoPerfil", "Grupo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupo> GrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("SistFlota_Seguridad_Modelo.GrupoPerfil", "Grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupo>("SistFlota_Seguridad_Modelo.GrupoPerfil", "Grupo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_Seguridad_Modelo", Name="Permiso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Permiso : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Permiso.
        /// </summary>
        /// <param name="iDpermiso">Valor inicial de la propiedad IDpermiso.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        public static Permiso CreatePermiso(global::System.String iDpermiso, global::System.String descripcion)
        {
            Permiso permiso = new Permiso();
            permiso.IDpermiso = iDpermiso;
            permiso.Descripcion = descripcion;
            return permiso;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDpermiso
        {
            get
            {
                return _IDpermiso;
            }
            set
            {
                if (_IDpermiso != value)
                {
                    OnIDpermisoChanging(value);
                    ReportPropertyChanging("IDpermiso");
                    _IDpermiso = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IDpermiso");
                    OnIDpermisoChanged();
                }
            }
        }
        private global::System.String _IDpermiso;
        partial void OnIDpermisoChanging(global::System.String value);
        partial void OnIDpermisoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "PermisoPerfil", "Perfil")]
        public EntityCollection<Perfil> Perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Perfil>("SistFlota_Seguridad_Modelo.PermisoPerfil", "Perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Perfil>("SistFlota_Seguridad_Modelo.PermisoPerfil", "Perfil", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SistFlota_Seguridad_Modelo", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="iDusuario">Valor inicial de la propiedad IDusuario.</param>
        /// <param name="nombreApellido">Valor inicial de la propiedad NombreApellido.</param>
        /// <param name="contraseña">Valor inicial de la propiedad Contraseña.</param>
        /// <param name="email">Valor inicial de la propiedad Email.</param>
        public static Usuario CreateUsuario(global::System.String iDusuario, global::System.String nombreApellido, global::System.String contraseña, global::System.String email)
        {
            Usuario usuario = new Usuario();
            usuario.IDusuario = iDusuario;
            usuario.NombreApellido = nombreApellido;
            usuario.Contraseña = contraseña;
            usuario.Email = email;
            return usuario;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDusuario
        {
            get
            {
                return _IDusuario;
            }
            set
            {
                if (_IDusuario != value)
                {
                    OnIDusuarioChanging(value);
                    ReportPropertyChanging("IDusuario");
                    _IDusuario = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IDusuario");
                    OnIDusuarioChanged();
                }
            }
        }
        private global::System.String _IDusuario;
        partial void OnIDusuarioChanging(global::System.String value);
        partial void OnIDusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreApellido
        {
            get
            {
                return _NombreApellido;
            }
            set
            {
                OnNombreApellidoChanging(value);
                ReportPropertyChanging("NombreApellido");
                _NombreApellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreApellido");
                OnNombreApellidoChanged();
            }
        }
        private global::System.String _NombreApellido;
        partial void OnNombreApellidoChanging(global::System.String value);
        partial void OnNombreApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contraseña
        {
            get
            {
                return _Contraseña;
            }
            set
            {
                OnContraseñaChanging(value);
                ReportPropertyChanging("Contraseña");
                _Contraseña = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contraseña");
                OnContraseñaChanged();
            }
        }
        private global::System.String _Contraseña;
        partial void OnContraseñaChanging(global::System.String value);
        partial void OnContraseñaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Habilitado
        {
            get
            {
                return _Habilitado;
            }
            set
            {
                OnHabilitadoChanging(value);
                ReportPropertyChanging("Habilitado");
                _Habilitado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Habilitado");
                OnHabilitadoChanged();
            }
        }
        private global::System.Boolean _Habilitado = true;
        partial void OnHabilitadoChanging(global::System.Boolean value);
        partial void OnHabilitadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo = false;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PrimerVez
        {
            get
            {
                return _PrimerVez;
            }
            set
            {
                OnPrimerVezChanging(value);
                ReportPropertyChanging("PrimerVez");
                _PrimerVez = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrimerVez");
                OnPrimerVezChanged();
            }
        }
        private global::System.Boolean _PrimerVez = true;
        partial void OnPrimerVezChanging(global::System.Boolean value);
        partial void OnPrimerVezChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SistFlota_Seguridad_Modelo", "UsuarioGrupo", "Grupo")]
        public EntityCollection<Grupo> Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grupo>("SistFlota_Seguridad_Modelo.UsuarioGrupo", "Grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grupo>("SistFlota_Seguridad_Modelo.UsuarioGrupo", "Grupo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
